/**
 * Install Script Generator
 *
 * Generates a bash setup script for Claude Code configuration.
 * This is for future npx @organized-ai/stack-init support.
 */

import type { StackComponent } from './export-generator';

/**
 * Generates a bash install script for the stack
 *
 * @param components - Array of components from the canvas
 * @param projectName - Name of the project
 * @returns Bash script content as a string
 */
export function generateInstallScript(
  components: StackComponent[],
  projectName: string
): string {
  const lines: string[] = [];

  // Header
  lines.push('#!/bin/bash');
  lines.push('');
  lines.push(`# Claude Code Setup Script for ${projectName}`);
  lines.push('# Generated by Organized AI Stack Builder');
  lines.push(`# Generated at: ${new Date().toISOString()}`);
  lines.push('');
  lines.push('set -e');
  lines.push('');

  // Start message
  lines.push('echo "🚀 Setting up Claude Code configuration..."');
  lines.push('');

  // Create directories
  lines.push('# Create .claude directory structure');
  lines.push('mkdir -p .claude/commands');
  lines.push('');

  // Get MCP components with install commands
  const mcps = components.filter((c) => c.type === 'mcp');
  const installCommands = mcps
    .filter((mcp) => mcp.config?.installCommand)
    .map((mcp) => mcp.config!.installCommand as string);

  // Add MCP install commands
  if (installCommands.length > 0) {
    lines.push('# Install MCP dependencies');
    installCommands.forEach((cmd) => {
      lines.push(`echo "Installing: ${cmd}"`);
      lines.push(cmd);
    });
    lines.push('');
  }

  // Completion message
  lines.push('echo ""');
  lines.push('echo "✅ Setup complete!"');
  lines.push('echo ""');
  lines.push('echo "Next steps:"');
  lines.push('echo "  1. Copy your configuration files to .claude/"');
  lines.push('echo "  2. Start Claude Code in this directory"');
  lines.push('');

  return lines.join('\n');
}

/**
 * Placeholder for future npx command support
 */
export function getQuickSetupCommand(projectName: string): string {
  const slug = projectName.toLowerCase().replace(/[^a-z0-9]+/g, '-');
  return `npx @organized-ai/stack-init ${slug}`;
}
